### ISSUE TITLE
Question about Multi-GPU training on single machine

### ISSUE THREAD

**Issue by CinKKKyo** [NVlabs/MUNIT#101]
I want to directly use nn.DataParallel()to implement  multi-gpu training but failed, I have find some related issues that if the model don't use the method forward() from nn.Module, the nn.DataParallel will not work. I saw there are several custom forward function in MUNIT. My question is how to implement nn.DataParallel(just data parallel so that I could use bigger batch)in MUNIT? Thanks for your help!

**Comment by lizijue** [comment]
Sorry to bother you @mingyuliutw  but I wanna know that is there any solution to use multiple GPUs in this version of code? I have tried for a long time by using 'torch.nn.parallel' but always failed as it only running in one GPU.

**Comment by zhihong-ni** [comment]
> 很抱歉打扰你@mingyuliutw 但我想知道在这个版本的代码中有没有使用多个 GPU 的解决方案？我已经尝试使用“torch.nn.parallel”很长时间了，但总是失败，因为它只在一个 GPU 上运行。

have you solved the problem? I also encountered the same issue.
