### ISSUE TITLE
in test.py line 42 needs to be fixed 

### ISSUE THREAD

**Issue by AllAwake** [NVlabs/MUNIT#13]
should be changed to trainer = MUNIT_Trainer(config)

otherwise it causes 
TypeError: __init__() takes 2 positional arguments but 3 were given

with the fix it works fine

**Comment by mingyuliutw** [comment]
Thanks. It is now fixed in commit [9121f3a8ef0a1cd85aa59bd3a091c32234a7be49](https://github.com/NVlabs/MUNIT/commit/9121f3a8ef0a1cd85aa59bd3a091c32234a7be49).
