### ISSUE TITLE
Update the requirements?

### ISSUE THREAD

**Issue by chrschorn** [NVlabs/MUNIT#16]
Hey,

when following the `USAGE.md` guide on Ubuntu 16 LTS, it was required to specify `pytorch=0.3` since 0.4 is now the latest version and the default. Also, `conda install -y -c anaconda yaml` doesn't work for me ("couldn't import yaml" etc.), maybe you meant pyyaml? I assume the same goes for the dockerfile.

My full installation that worked with the Testing section of `USAGE.md`:

```
conda install pytorch=0.3 torchvision -c pytorch
conda install -y -c anaconda pip
conda install -y -c anaconda pyyaml
pip install tensorboard tensorboardX
```

PyTorch 0.3 defaults to cuda 8.0

**Comment by Ben-Louis** [comment]
For yaml, you can try `pip install PyYAML`, I solved it in this way.

**Comment by chrschorn** [comment]
I know, this is what this issue and the pull request is about :-) I think the instructions should be updated.
