### ISSUE TITLE
Dataset Arrangement

### ISSUE THREAD

**Issue by akashdexati** [NVlabs/MUNIT#2]
Hi NVlabs
Can you please explain the dataset arrangement.
**1).** The folders name TrainA - TrainB - TestA - TestB. What type of images are we supposed to place.
**2).** How do we specify the style images. ?

**Comment by xunhuang1995** [comment]
1) You can place the following types of images.
IMG_EXTENSIONS = [
    '.jpg', '.JPG', '.jpeg', '.JPEG',
    '.png', '.PNG', '.ppm', '.PPM', '.bmp', '.BMP',
]
2) You can specify style images at test time as described in the "Example-guided Translation" section in the [user manual page](https://github.com/NVlabs/MUNIT/blob/master/USAGE.md). At training time you don't need to specify style images.

**Comment by akashdexati** [comment]
TrainA & TrainB are two different folders. Is it related to source(target) to target(source).
Can you please provide any sample image that is to be placed in these folders. ?

**Comment by AidasK** [comment]
Datasets structure could be explained in the usage.md because now it's a bit confusing. 

As I can see in `datasets/demo_edges2handbags`:
trainA and trainB are random unrelated source and target images. (Unpaired data as stated in paper)
testA and testB are related source and target images. (Paired data)

Can testA and testB be unpaired too?

**Comment by abhishekcvedia** [comment]
I have the same doubt as @AidasK
Are we supposed to have paired dataset in trainA and trainB??
@akashdexati @mingyuliutw @xunhuang1995

**Comment by Cuky88** [comment]
Let's consider you have 2 sets of image collections (unpaired) of a national park. One collection has images of the park in summer (domain 1) and the other one images in winter (domain 2). Than, you can put domain 1 in trainA and domain 2 in trainB. For testing you will also need images, therefore you take some of your domain 1 images from trainA and put them in testA, and you do the same for domain 2, take some images from trainB and put them in testB. The images in trainA and trainB are unpaired, so are the images in testA and testB. 

It is just important that the 2 image collections (summer and winter) show the same content, e.g. the national park, so they don't need to be paired.
