### ISSUE TITLE
Can not find Animal Image Translation dataset

### ISSUE THREAD

**Issue by MichinariNukazawa** [NVlabs/MUNIT#22]
Can I get Animal Image Translation dataset?
Can not find resource url in MUNIT user manual, paper and pytorch-CycleGAN-and-pix2pix project.

**Comment by mingyuliutw** [comment]
@MichinariNukazawa Due to the copyright issue, we cannot release the datasets. However, we describe how we extract the cropped animal faces in [UNIT Issue 27 ](https://github.com/mingyuliutw/UNIT/issues/27).

**Comment by MichinariNukazawa** [comment]
Thanks.
