### ISSUE TITLE
How to get the data results of LPIPS Distance

### ISSUE THREAD

**Issue by WorkingCC** [NVlabs/MUNIT#25]
Your work gets surprising results and I expect to reproduce the data of LPIPS distance that you list in Table1. Given one input image, you sample 19 outputs. For every input(edges), do you calculate the LPIPS distance between the given image(edges) and corresponding 19 samples(handbags) ? After that, you sum those 19 groups of data and have a average? Is it the same to other 99 input images in your experiment ? I'm confused about this and looking forward to your reply, thank you!

**Comment by xunhuang1995** [comment]
Given one input image, we sample 19 **pairs** of outputs (randomly sample two style vectors and generate two images). We then compute the distance between two output images and get an average.

**Comment by MilanKolkata** [comment]
Just for making sure, you generate the output images with random two style vectors and do this process 19 times, get 19 pairs of the output images and compute the distance of each pair and get an average finally. Do I understand correctly?
Thank you!

**Comment by xunhuang1995** [comment]
Yes.

**Comment by greatmanqss** [comment]
So sampling 38 styles in one time is equal to sampling 19 pairs?
