### ISSUE TITLE
[request] code for calculating CIS and IS score

### ISSUE THREAD

**Issue by coolKeen** [NVlabs/MUNIT#26]
Nice paper! Could you please release the code for calculating CIS and IS score?

**Comment by Cuky88** [comment]
@mingyuliutw Any information about releasing code for CIS and IS? Would really appreciate it.

**Comment by Hshihua** [comment]
@mingyuliutw  Looking forward to the codes, too. Many thanks.

**Comment by xunhuang1995** [comment]
I just uploaded the code for calculating CIS and IS score.

**Comment by Hshihua** [comment]
@xunhuang1995 Many thanks for such nice work! You stated that you have finetuned the Inception V3 model for calculating the IS as well as CIS in this paper, does it really need to be finetuned?
