### ISSUE TITLE
can you share data ?

### ISSUE THREAD

**Issue by taki0112** [NVlabs/MUNIT#3]
Hi
Very awesome works
I implemented MUNIT in tensorflow, very thank you share it !!!

Can you share the data you used to animal image translation ? 
I am also interested in image-to-image translation, and I wish I could get a dataset.

**Comment by xunhuang1995** [comment]
Thanks for your interests. As described [here](https://github.com/mingyuliutw/UNIT/issues/27) we do not have the right to share the dataset. However we will release the pretrained models soon.
