### ISSUE TITLE
      The "freeze_support()" line can be omitted if the program

### ISSUE THREAD

**Issue by c1a1o1** [NVlabs/MUNIT#30]
C:\Users\caocao\Anaconda3\python.exe D:/work/gan-pix2pix/MUNIT-master/train.py --config configs/edges2shoes_folder.yaml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
Traceback (most recent call last):
  File "D:/work/gan-pix2pix/MUNIT-master/train.py", line 60, in <module>
    prepare(preparation_data)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\caocao\Anaconda3\lib\runpy.py", line 254, in run_path
    for it, (images_a, images_b) in enumerate(zip(train_loader_a, train_loader_b)):
  File "C:\Users\caocao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\caocao\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\caocao\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\work\gan-pix2pix\MUNIT-master\train.py", line 60, in <module>
    for it, (images_a, images_b) in enumerate(zip(train_loader_a, train_loader_b)):
  File "C:\Users\caocao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
        return _DataLoaderIter(self)return _DataLoaderIter(self)

  File "C:\Users\caocao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
  File "C:\Users\caocao\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()
    w.start()  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\process.py", line 105, in start

  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\process.py", line 105, in start
        self._popen = self._Popen(self)
self._popen = self._Popen(self)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
        return _default_context.get_context().Process._Popen(process_obj)return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 34, in __init__
    return Popen(process_obj)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 144, in get_preparation_data
    reduction.dump(process_obj, to_child)
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\reduction.py", line 59, in dump
    _check_not_importing_main()
  File "C:\Users\caocao\Anaconda3\lib\multiprocessing\spawn.py", line 137, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by mingyuliutw** [comment]
@c1a1o1 This line of code is not in our repository.

**Comment by Altosm** [comment]
I got the same error and fixed it with adding the following line in the train.py after the import section:
if __name__ == '__main__':
   "the rest of the codes in train.py"

source: https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

**Comment by rickkk856** [comment]
It took me sometime to figure out what I was doing wrong so, to fix this error change `train.py` to the code bellow

```
from utils import get_all_data_loaders, prepare_sub_folder, write_html, write_loss, get_config, write_2images, Timer
import argparse
from torch.autograd import Variable
from trainer import MUNIT_Trainer, UNIT_Trainer
import torch.backends.cudnn as cudnn
import torch
try:
    from itertools import izip as zip
except ImportError: # will be 3.x series
    pass
import os
import sys
import tensorboardX
import shutil


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str, default='configs/edges2handbags_folder.yaml', help='Path to the config file.')
    parser.add_argument('--output_path', type=str, default='.', help="outputs path")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument('--trainer', type=str, default='MUNIT', help="MUNIT|UNIT")
    opts = parser.parse_args()

    cudnn.benchmark = True

    # Load experiment setting
    config = get_config(opts.config)
    max_iter = config['max_iter']
    display_size = config['display_size']
    config['vgg_model_path'] = opts.output_path
    
    # Setup model and data loader
    if opts.trainer == 'MUNIT':
        trainer = MUNIT_Trainer(config)
    elif opts.trainer == 'UNIT':
        trainer = UNIT_Trainer(config)
    else:
        sys.exit("Only support MUNIT|UNIT")
    trainer.cuda()
    train_loader_a, train_loader_b, test_loader_a, test_loader_b = get_all_data_loaders(config)
    train_display_images_a = torch.stack([train_loader_a.dataset[i] for i in range(display_size)]).cuda()
    train_display_images_b = torch.stack([train_loader_b.dataset[i] for i in range(display_size)]).cuda()
    test_display_images_a = torch.stack([test_loader_a.dataset[i] for i in range(display_size)]).cuda()
    test_display_images_b = torch.stack([test_loader_b.dataset[i] for i in range(display_size)]).cuda()

    # Setup logger and output folders
    model_name = os.path.splitext(os.path.basename(opts.config))[0]
    train_writer = tensorboardX.SummaryWriter(os.path.join(opts.output_path + "/logs", model_name))
    output_directory = os.path.join(opts.output_path + "/outputs", model_name)
    checkpoint_directory, image_directory = prepare_sub_folder(output_directory)
    shutil.copy(opts.config, os.path.join(output_directory, 'config.yaml')) # copy config file to output folder

    # Start training
    iterations = trainer.resume(checkpoint_directory, hyperparameters=config) if opts.resume else 0
    while True:
        for it, (images_a, images_b) in enumerate(zip(train_loader_a, train_loader_b)):
            trainer.update_learning_rate()
            images_a, images_b = images_a.cuda().detach(), images_b.cuda().detach()

            with Timer("Elapsed time in update: %f"):
                # Main training code
                trainer.dis_update(images_a, images_b, config)
                trainer.gen_update(images_a, images_b, config)
                torch.cuda.synchronize()

            # Dump training stats in log file
            if (iterations + 1) % config['log_iter'] == 0:
                print("Iteration: %08d/%08d" % (iterations + 1, max_iter))
                write_loss(iterations, trainer, train_writer)

            # Write images
            if (iterations + 1) % config['image_save_iter'] == 0:
                with torch.no_grad():
                    test_image_outputs = trainer.sample(test_display_images_a, test_display_images_b)
                    train_image_outputs = trainer.sample(train_display_images_a, train_display_images_b)
                write_2images(test_image_outputs, display_size, image_directory, 'test_%08d' % (iterations + 1))
                write_2images(train_image_outputs, display_size, image_directory, 'train_%08d' % (iterations + 1))
                # HTML
                write_html(output_directory + "/index.html", iterations + 1, config['image_save_iter'], 'images')

            if (iterations + 1) % config['image_display_iter'] == 0:
                with torch.no_grad():
                    image_outputs = trainer.sample(train_display_images_a, train_display_images_b)
                write_2images(image_outputs, display_size, image_directory, 'train_current')

            # Save network weights
                if (iterations + 1) % config['snapshot_save_iter'] == 0:
                    trainer.save(checkpoint_directory, iterations)

            iterations += 1
            if iterations >= max_iter:
                sys.exit('Finish training')
```

**Comment by Czshippee** [comment]
I also encounter this problem and want to ask why this problem will happen?
Why we need put all code inside the 'if __name__ == '__main__':' ?
Why we put code outside will cause this problem? Thanks

**Comment by hardikRumbum** [comment]
The reason for putting the code inside the if __name__ == '__main__' block is to ensure that the code inside the block is only executed when the script is run as the main program, and not when the module is imported by another script.

This is because when a Python script is run, the __name__ variable is set to '__main__'. When a module is imported by another script, the __name__ variable is set to the name of the module.

If you put your code outside the if __name__ == '__main__' block, it will be executed even when the module is imported by another script. This can lead to unexpected behavior, such as the code being executed multiple times, or global variables being modified unintentionally.

Putting the code inside the if __name__ == '__main__' block ensures that the code is only executed when the script is run as the main program. This can help prevent issues with unexpected behavior or unintended side effects.

I hope this helps clarify why it's important to put your code inside the if __name__ == '__main__' block. Let me know if you have any further questions!

**Comment by hardikRumbum** [comment]
> I also encounter this problem and want to ask why this problem will happen? Why we need put all code inside the 'if **name** == '**main**':' ? Why we put code outside will cause this problem? Thanks

The reason for putting the code inside the if __name__ == '__main__' block is to ensure that the code inside the block is only executed when the script is run as the main program, and not when the module is imported by another script.

This is because when a Python script is run, the __name__ variable is set to '__main__'. When a module is imported by another script, the __name__ variable is set to the name of the module.

If you put your code outside the if __name__ == '__main__' block, it will be executed even when the module is imported by another script. This can lead to unexpected behavior, such as the code being executed multiple times, or global variables being modified unintentionally.

Putting the code inside the if __name__ == '__main__' block ensures that the code is only executed when the script is run as the main program. This can help prevent issues with unexpected behavior or unintended side effects.

I hope this helps clarify why it's important to put your code inside the if __name__ == '__main__' block. Let me know if you have any further questions!
