### ISSUE TITLE
edge2shoes dataset question

### ISSUE THREAD

**Issue by coolKeen** [NVlabs/MUNIT#31]
Nice paper!
Could you please describe how you process the shoes using HED algorithm in more details?
I follow the instruction in [here](https://github.com/phillipi/pix2pix/tree/master/scripts/edges) but the edge images I create are not as smooth as yours, e.g.
![7242087 375089](https://user-images.githubusercontent.com/20871576/43508787-75671a22-95a3-11e8-8dcd-34918eb0a62b.jpg)
There are two type of image size(ut-zap50k-images,ut-zap50k-images-square) in the ut-zap50k data set, which one do you use?  Or could you release the edge images you create？
Thanks in advance~

**Comment by mingyuliutw** [comment]
@coolKeen We didn't process the edges ourselves. We download the datasets from the pix2pix project (Your link also points to that project.).
