### ISSUE TITLE
RuntimeError when set vgg_w=1

### ISSUE THREAD

**Issue by MilanKolkata** [NVlabs/MUNIT#33]
I am trying to reproducing the results of SYNTHIA-City and set hyperparameter vgg_w=1, there is an error as below.

Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f7bf31bbb10>> ignored
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f7bf31a7ed0>> ignored
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    trainer.gen_update(images_a, images_b, config)
  File "/workspace/trainer.py", line 100, in gen_update
    self.loss_gen_vgg_a = self.compute_vgg_loss(self.vgg, x_ba, x_b) if hyperparameters['vgg_w'] > 0 else 0
  File "/workspace/trainer.py", line 119, in compute_vgg_loss
    img_vgg = vgg_preprocess(img)
  File "/workspace/utils.py", line 245, in vgg_preprocess
    batch = batch.sub(Variable(mean)) # subtract mean
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'

There is no error when I set vgg_w=0, should I set other hyperparameters?
Thank you!

**Comment by MilanKolkata** [comment]
Thanks so much! It helps me a lot!

**Comment by mingyuliutw** [comment]
Thanks @Cuky88 for the explanation. Just want to clarify. The loss is called `domain invariant perceptual loss`. It is different to perceptual loss. Please check out our paper for more details.
