### ISSUE TITLE
Different slerp implementation than reference

### ISSUE THREAD

**Issue by Cuky88** [NVlabs/MUNIT#34]
I'm trying to do some interpolations and latent space exploration. The [slerp code](https://github.com/ptrblck/prog_gans_pytorch_inference/blob/master/utils.py#L69) from the progressive GAN repo is slightly different than your implementation. 

You are not setting the low value to the previous high value in the loop. Is there a certain reason why you changed the code?

I'm not really deep into this topic, so I appreciate your answer.

**Comment by xunhuang1995** [comment]
Both implementations are fine. The original one generates a single smoothly-changing video, while this one generates several short videos that interpolates between two points.
