### ISSUE TITLE
If total domains are 4

### ISSUE THREAD

**Issue by redhat12345** [NVlabs/MUNIT#36]
Hi,

Thank you so much for the code and paper. My dataset contains 4 domains. The dataset structure is: trainA, trainB, trainC, trainD, testA, testB, testC, testD. How can I use this code for generating images images if 4 domains are exist in the dataset? Thanks in advanced.

**Comment by xunhuang1995** [comment]
You can either train a model for each pair of domains, or adapting existing multi-domain image translation methods (such as [StarGAN](https://arxiv.org/abs/1711.09020)) to our framework.
