### ISSUE TITLE
No activation at the end of the ResBlock?

### ISSUE THREAD

**Issue by justanhduc** [NVlabs/MUNIT#39]
Hi.
I have a question regarding the implementation of the ResBlock [here](https://github.com/NVlabs/MUNIT/blob/d0fe9286c24b2a67bbab90d5192d1c01f285d948/networks.py#L286). I figured out that the output of the ResBlock does not have any activation and it is input directly to the next block. I would like to confirm if it is a bug or the authors' intention. Thanks in advance!

**Comment by xunhuang1995** [comment]
It's not a bug. See [this paper](https://arxiv.org/pdf/1603.05027.pdf) and also [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/networks.py)
