### ISSUE TITLE
Config Day2Night | Split Datasets

### ISSUE THREAD

**Issue by SoleSensei** [NVlabs/MUNIT#52]
Hi, there, i'm trying to train dataset and stucked with some learning problems

**Example** of 10000 iterations day 2 night (train)
![image](https://user-images.githubusercontent.com/24857057/50388395-345a5e00-0726-11e9-95ab-60b9b549572c.png)
**Example** of 10000 iterations night 2 day (train)
![image](https://user-images.githubusercontent.com/24857057/50388408-7edbda80-0726-11e9-9de0-8a257573d44e.png)

I think that it's `unit_day2night.yaml` configuration problem. Can you share yours config file?

---

Another option, that it's **dataset's split** issue.
I used **50/50** for train and test. And both divided into two equal domains A and B.

**Comment by Cuky88** [comment]
@SoleSensei 
Hi, can you tell me where you got the dataset?

**Comment by SoleSensei** [comment]
@Cuky88,
It is [NEXET dataset](https://blog.getnexar.com/https-medium-com-itayklein-intro-nexet-50e9b596d0e5)

**Comment by SoleSensei** [comment]
Thats okay. I resolved this with splitting 20/80 and removing mismatch labels from train data.
