### ISSUE TITLE
Is is able to train with --trainer "UNIT"?

### ISSUE THREAD

**Issue by doantientai** [NVlabs/MUNIT#53]
Thank you very much for the awesome implementation. I have successfully trained MUNIT with my own data.

I am trying training with --trainer UNIT, with exactly the same dataset and yaml config. However, the following error shown up. I am guessing that either x_aba or x_a is NoneType because of some reasons that I haven't found out. It would be nice if you can provide some help. Thank you very much!

`Traceback (most recent call last):
  File "train.py", line 67, in <module>
    trainer.gen_update(images_a, images_b, config)
  File "/media/tai/6TB/Projects/MUNIT/trainer.py", line 282, in gen_update
    self.loss_gen_cyc_x_a = self.recon_criterion(x_aba, x_a)
  File "/media/tai/6TB/Projects/MUNIT/trainer.py", line 238, in recon_criterion
    return torch.mean(torch.abs(input - target))
  File "/home/tai/anaconda3/envs/pytorch_p3/lib/python3.6/site-packages/torch/tensor.py", line 322, in __rsub__
    return -self + other
TypeError: add() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (Tensor other, Number alpha)
 * (Number other, Number alpha)`

**Comment by doantientai** [comment]
So I spent sometime digging a bit into the repo of MUNIT and UNIT. It turns out that UNIT uses 3 additional parameters. I found them in the yaml files in the github of UNIT:

recon_kl_w: 0.01              # weight of KL loss for reconstruction
recon_x_cyc_w: 10             # weight of cycle consistency loss
recon_kl_cyc_w: 0.01          # weight of KL loss for cycle consistency 

So basically if anyone want to run UNIT using this github, please add these 3 parameters to your config yaml file. I hope this may help other saving some time.

**Comment by LuletterSoul** [comment]
Thanks so much, it helps we a lot.
