### ISSUE TITLE
housecat2dog.pt model test results

### ISSUE THREAD

**Issue by EoAelinr** [NVlabs/MUNIT#55]
Hello.

I tried to replicate the results of your paper with your code and model for the housecat2dog case, but do not obtain results of the same quality. I used the same .yaml as edge2shoes, as indicated in #46, and the cat picture is one of those you showcase.
The command I used is `python test.py --config configs/housecats2dogs_folder.yaml --input inputs/cat_paper.jpg --output_folder outputs --checkpoint models/housecat2dog.pt --a2b 1`

What am I doing wrong ?

**input :**
![input](https://user-images.githubusercontent.com/47625749/52774377-547b0f00-303d-11e9-9ccd-0a419ead6779.jpg)
**output :**
![output008](https://user-images.githubusercontent.com/47625749/52774235-0cf48300-303d-11e9-8f0b-daf8cfb3f077.jpg)
![output000](https://user-images.githubusercontent.com/47625749/52774347-44632f80-303d-11e9-886b-62e108f54c1e.jpg)
![output002](https://user-images.githubusercontent.com/47625749/52774351-475e2000-303d-11e9-8d7d-79ccce500f37.jpg)
![output005](https://user-images.githubusercontent.com/47625749/52774362-4b8a3d80-303d-11e9-8f16-74deb24f4a65.jpg)

**Comment by mingyuliutw** [comment]
I guess you are using a different dataset?

**Comment by mingyuliutw** [comment]
Are you using pytorch 0.4.1?

**Comment by EoAelinr** [comment]
I do.
I installed the dependencies as suggested in USAGE.md :
```
conda install pytorch=0.4.1 torchvision cuda91 -c pytorch;
conda install -y -c anaconda pip;
conda install -y -c anaconda pyyaml;
pip install tensorboard tensorboardX;
```

**Comment by mingyuliutw** [comment]
I will take a look later this week. Meanwhile, could you check out the first few commit to test the code. The code was developed using an earlier pytorch version. I hope there is no mismatch.

**Comment by EoAelinr** [comment]
Thank you.
I reverted to pytorch 0.3 and tested a few commits before the "compatibility update for pytorch 0.4" 1337c260539a21368cc42278bf6b4c9cbcada4d6 commit (the earliest being e014bc06786bf9062103323df5e4c437ebce5253 from the 16 April).
The generated images were different from those of the latest versions but not better :
![output009](https://user-images.githubusercontent.com/47625749/52791479-52c74080-3069-11e9-91f0-1456c9a4afb3.jpg)
![output007](https://user-images.githubusercontent.com/47625749/52791489-5955b800-3069-11e9-8cbf-6232f8d22078.jpg)
![output000](https://user-images.githubusercontent.com/47625749/52791445-375c3580-3069-11e9-8d05-036cb8fa1f09.jpg)

**Comment by mingyuliutw** [comment]
Thanks for the info. I will take a look.

**Comment by xunhuang1995** [comment]
I just checked into it and the results seem reasonable to me. When you randomly sample the style code, not all images will look that good. For example, I found German Shepherd and Husky are usually more difficult to generate than Samoyed.

**Comment by Williamongh** [comment]
I used the same cat and got the same bad pictures.
THIS CAT was the cat you used in README.md.
