### ISSUE TITLE
What's your advice about the setting of reconstruct loss weight: aba?

### ISSUE THREAD

**Issue by beginner1997** [NVlabs/MUNIT#60]
I'm now training this NN to learn to translate nighttime images to daylight images. However the result is not that fine like yours. The default setting of recon_x_cyc_w is 0, so I wonder if it will go better if take it into account? And if it is, could you tell about the value that you recommend?
I'm doing this work for my graduate study. I would appreciate it if you could reply me.

**Comment by xunhuang1995** [comment]
If the you want the translation to be pixel-wise aligned, setting recon_x_cyc_w to a high value (like 10) should help.
If the translation involves shape transformations (e.g., dog to cat), we find recon_x_cyc_w to be unnecessary and sometimes detrimental.

For day to night translation, I think you should set recon_x_cyc_w to a high value.
