### ISSUE TITLE
How to train the MLP, to generate AdaIN parameters

### ISSUE THREAD

**Issue by hujinsen** [NVlabs/MUNIT#65]
The paper applies MLP to generate AadIN parameters, but how is the MLP trained?
![image](https://user-images.githubusercontent.com/6258078/58462318-30fb5080-8164-11e9-9f08-99ddd6d4da3a.png)

**Comment by xunhuang1995** [comment]
https://github.com/NVlabs/MUNIT/blob/a99d853ab3d5fda837395c821a7a65d46afdebb4/networks.py#L109
