### ISSUE TITLE
test.py parser argument : a2b

### ISSUE THREAD

**Issue by gcosne** [NVlabs/MUNIT#66]
The value for a2b option should be zero in the case of a translation from b2a.
The comment in the parser seems incorrect to me: 
`parser.add_argument('--a2b', type=int, default=1, help="1 for a2b and others for b2a")`

Further in the test.py: `encode = trainer.gen_a.encode if opts.a2b else trainer.gen_b.encode`

This IF statement: **if opts.a2b** pass when opts.a2b is anything but zero.

**Comment by xunhuang1995** [comment]
It is indeed incorrect. I just fixed it. Thank you for the feedback!
