### ISSUE TITLE
Test.py parser argument

### ISSUE THREAD

**Issue by gcosne** [NVlabs/MUNIT#69]
Hello, I wonder what is the use of these arguments ? They do have the same help and I don't understand what we are trying to synchronize here ?

```
parser.add_argument('--synchronized', action='store_true', help="whether use synchronized style code or not")
parser.add_argument('--output_only', action='store_true', help="whether use synchronized style code or not")
```

Thank you for your help

**Comment by xunhuang1995** [comment]
When `opts.synchronized=True`, the model generates M * N images with M different content and N different styles. When it's false, the model generates M * N different styles.

I will fix the help of `output_only`

**Comment by gcosne** [comment]
Thank you for your reply, it's clear to me now
