### ISSUE TITLE
image alignment

### ISSUE THREAD

**Issue by fengjunlv** [NVlabs/MUNIT#7]
Thanks for sharing the code of this amazing work with us.  A quick question: In your house cats <-> big cats example, are those cat faces properly cropped and aligned before training?

**Comment by mingyuliutw** [comment]
The answer is yes and no. Those cats and dogs are cropped by a template matching algorithm briefly described in [issue#27 of UNIT repo](https://github.com/mingyuliutw/UNIT/issues/27). The provided templates are roughly aligned. But the template matching algorithm is not perfect. Hence, the faces are not well aligned.

**Comment by fengjunlv** [comment]
Thanks for the clarification.  Have you tried translation between objects with significantly different appearance, for example, human faces <-> cat faces?
