### ISSUE TITLE
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument

### ISSUE THREAD

**Issue by bolin12** [NVlabs/MUNIT#83]
when i run python test.py --config configs/edges2shoes_folder.yaml --input inputs/edges2shoes_edge.jpg --output_folder outputs --checkpoint models/edges2shoes.pt --a2b 1

I got this information
my machine:

RTX2080
Driver Version: 430.50
CUDA Version: 10.1

# packages in environment at /home/lbl/miniconda3/envs/MUNIT:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2019.10.16                    0    anaconda
certifi                   2019.9.11                py36_0    anaconda
cffi                      1.13.2           py36h8022711_0    conda-forge
cuda91                    1.0                  h4c16780_0    pytorch
freetype                  2.10.0               he983fc9_1    conda-forge
intel-openmp              2019.4                      243    defaults
jpeg                      9c                h14c3975_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                hc3755c2_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mkl                       2019.4                      243    defaults
ncurses                   6.1               hf484d3e_1002    conda-forge
ninja                     1.9.0                hc9558a2_1    conda-forge
numpy                     1.17.3           py36h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1                h7b6447c_0    anaconda
pillow                    6.2.1            py36hd70f55b_1    conda-forge
pip                       19.3.1                   py36_0    anaconda
pycparser                 2.19                     py36_1    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
pyyaml                    5.1.2            py36h7b6447c_0    anaconda
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.6.0                   py36_1    conda-forge
six                       1.13.0                   py36_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
torchvision               0.2.1                      py_2    pytorch
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7                h96e3832_1    anaconda
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

**Comment by Jessicall** [comment]
@BolinLi-s ,Hi,I have the same problem.Have you solved it?

**Comment by yindavidyang** [comment]
Conda uninstall cuda91, and install cuda92 instead.

**Comment by dragen1860** [comment]
Use pytorch 1.x. this error will disappear. just commnet `load_lua` import line.
