### ISSUE TITLE
inception checkpoint?

### ISSUE THREAD

**Issue by sjytker** [NVlabs/MUNIT#96]
I am new to this area and I want to run test_batch.py.  How to find a usable inception module?

**Comment by Raoshijin** [comment]
Hoe did you solve this problem?

**Comment by sjytker** [comment]
> Hoe did you solve this problem?

Just download it from somewhere else, modelzoo or likewise, I've forgotten the details.

**Comment by Raoshijin** [comment]
I also wonder if the checkpoint of inception_a is the same of inception_b
